### ISSUE TITLE
Pageable: optimisation of page rendering to avoid potential visual glitch

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/deliteful#100]
See https://github.com/sbrunot/deliteful/commit/60b00989bd479884e18ce226aa2eb6c8329d6e06#list-pageable-js-P505

The idea is to render pages before (or after) page loader widgets to avoid having to move the widget when the page has been loaded.

Here is the original idea by @wkeese:

It would make sense to change the signature of `_renderNewItems()` to take an optional "before" node, rather than a boolean:

```
_renderNewItems: function (/*Array*/ items, /*Element?*/ beforeNode) {
```

When `beforeNode` is specified, `_renderNewItems()` would call  would call `this.containerNode.insertBefore(item, beforeNode)` rather than `appendChild()`.

Then in `_previousPageReadyHandler` and `_nextPageReadyHandler`  you just call `this._renderNewItems(items,  this._previousPageLoader.nextSiblingChild)` and `this._renderNewItems(items,  this._nextPageLoader)`.

**Comment by wkeese** [comment]
> My newer comments actually supercede the one you quoted. My current suggestion, to fix a number of issues, is that List should have a `containerNode` for all the ListItems, and that the loading panel and next/previous buttons (aka "loader widgets") should be outside of it:

This was implemented in 3338825d03ab7b66152fd7bcae9d30d9428c2fff.
