### ISSUE TITLE
List enhancement request: support definition of custom renderers templates in markup

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/deliteful#169]
This feature is inspired by a similar one offered by the core-list component of polymer. To simplify the customisation of item renderers / category renderers for `deliteful/List`, I think a nice feature would be to allow defining custom renderers templates in markup, as in the following example:

``` html
<d-list ...>
    <item-renderer-template>
   ...
    </item-renderer-template>
    <category-renderer-template>
    ...
    </category-renderer-template>
</d-list>
```

If either `<item-renderer-template>`or `<category-renderer-template>` is found by the list, it would create and assign to itself a custom item renderer / a custom category renderer that uses the template.

**Comment by wkeese** [comment]
Closing this since we have no current plans to implement it.
