### ISSUE TITLE
TextBox element

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#175]

**Comment by edchat** [comment]
I wanted to get the Textbox support working with the latest updates to delite and deliteful in case it will be used later.  The latest is here: https://github.com/edchat/deliteful/tree/textbox3
My latest Textbox support, rebased on the latest deliteful. This drop is still using the template, I ran into problems when I tried to remove it so I am still using it. It also includes a temporary TextboxSample for testing, a better sample will be used in place of this one later.

**Comment by wkeese** [comment]
Closing this since we have no current plans to finish implementing it.
