### ISSUE TITLE
Search/FilterBox element

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#179]
This should include integration with List as FilteredList

**Comment by AdrianVasiliu** [comment]
Some comments at https://github.com/ibm-js/deliteful/pull/449 might be relevant for the design of this new widget(s) and for their integration with Combobox.

**Comment by AdrianVasiliu** [comment]
PS I refer in particular to these comments from #449:
* https://github.com/ibm-js/deliteful/pull/449#issuecomment-69435625
* https://github.com/ibm-js/deliteful/pull/449#issuecomment-69531579
* https://github.com/ibm-js/deliteful/pull/449#issuecomment-69568366

**Comment by wkeese** [comment]
Closing this since we have no current plans to implement it.
