### ISSUE TITLE
Investigate how to handle the css layout approach vs use cases that need to rely on javascript resize

### ISSUE THREAD

**Issue by pruzand** [ibm-js/deliteful#22]
The css layout approach taken in deliteful excludes the cases where a child widget needs to react to a resize event. For example, a Chart would need to do some computation to rearrange its components (scale, plot, etc) according to the new size. In dijit, the containers notifies its children of a size change. With the css approach, there's no such notification.

**Comment by cjolif** [comment]
Closing this for now. Given the current scope we don't really need this but we might have to look into it again later.
