### ISSUE TITLE
deliteful/List: problem with SHIFT + TAB in Firefox 31.0 ESR 

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/deliteful#244]
How to reproduce:
1. Load the test page `deliteful/tests/functional/list/list-mark-1.html` in Firefox 31.0 ESR
2. Press the `TAB` key: the first item of the list receives the focus
3. Press the `ARROW DOWN` key to focus the second item
4. Press `SHIFT + TAB`

=> The focus is given to the first item of the list, instead of being given to the input field at the top of the page

**Comment by wkeese** [comment]
I tried this on the current Firefox ESR, 52.2.1. Besides the special Firefox behavior where the List itself gets focus, because it is scrollable, I don't see any issue.  Definitely not the issue reported in this ticket.
