### ISSUE TITLE
deliteful/Button: fix iOS theme

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/deliteful#275]
The current ios themes for button differs from the native theme.

Here are a few examples (that can be seen using the `deliteful/demos/kittens/app.html` on ios platforms:
1. labels are not vertically centred in button:

![ios-button](https://cloud.githubusercontent.com/assets/3638165/4203620/bdb7b5d6-3830-11e4-9a93-14a4b600c710.png)
1. default sizing seems wrong:

![ios-button2](https://cloud.githubusercontent.com/assets/3638165/4203661/1cc8ee1e-3831-11e4-9344-c0e7421fa4cb.png)

**Comment by wkeese** [comment]
Closing this because we have no longer have plans to support the ios theme.
