### ISSUE TITLE
tests: leverage this.skip() when you need to skip tests

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#304]
As mentioned in http://www.sitepen.com/blog/2014/09/12/intern-2-1-released/,

> Test writers can also programmatically skip tests using the new skip function. A test can call this.skip(<message>) at any time to halt execution and move to the next test. The skip message will be reported by all built-in reporters, as well as any custom reporters that listen for the new /test/skip message.

So, I guess it's better to do:

```js
if (/safari|iPhone|selendroid/.test(remote.environmentType.browserName) || remote.environmentType.safari) {
	return this.skip("no support for moveTo, skipping tests...");
```

rather than

```js
if (/safari|iPhone|selendroid/.test(remote.environmentType.browserName) || remote.environmentType.safari) {
	return remote
		.then(logMessage(remote, this.id, "no support for moveTo, skipping tests..."));
```

Likewise for code like:

```js
if (/safari|iphone|selendroid/.test(remote.environmentType.browserName)) {
	// SafariDriver doesn't support sendKeys
	console.log("Skipping test: key nav as sendKeys not supported on Safari");
	return remote.end();
}
```

I did it in delite, see ibm-js/delite@1daf7e329523ff8d24407aa9d5eb83119cdb7dcc.

See also #282.

**Comment by wkeese** [comment]
Looks like this was completed already in c9a95cc19566faa262068ab3be3e1bad2976f463, right @edchat ?

**Comment by edchat** [comment]
@wkeese you are correct.
