### ISSUE TITLE
ComboBox: implement keyboard navigation support

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/deliteful#362]
Keyboard navigation in the combo implies:
* Ensure key events arrive at the List widget inside the popup.
* Ensure the navigation inside the List produces the expected effects on the combo widget.

Prerequisites:
* To help for implementing keyboard navigation for the combo, @wkeese has done changes for delite/KeyNav in ibm-js/delite/pull/302 and ibm-js/delite/pull/309. 

Next steps:
* Solve the remaining obstacles to get the keyboard navigation for the combobox.
* Related:
  * "List widget: conflicting "space" keyboard shortcut" (#332)
  * "List/KeyNav: could/should rely on aria-activedescendant instead of focus for managing item navigation?" (#331)

**Comment by cjolif** [comment]
And document it once done.

**Comment by AdrianVasiliu** [comment]
Thanks @wkeese. Pushed via 36ec767a598157a61ada2566c4feee24e8dd42a8.

Also pushed this fix: 7a85aaccd27d2b9efec4d40b94ddd774650d6236 to avoid closing the popup when clicking a list category item, which was a regression I previously introduced (thus removed the TODO from your PR).
