### ISSUE TITLE
cleanup git history

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#389]
This is deliteful counterpart to ibm-js/delite#321

**Comment by cjolif** [comment]
result is not perfect as we still get old commits on files that were kept with the same name even if totally different but I guess this is ok at least for now.

**Comment by wkeese** [comment]
Thanks for doing that.

Theoretically it's possible to get to perfect by squashing all the old commits into a single one.   For example, squash dfccf97c016126fc26fab72d9119c25c8ddf67ab  to b39692cc8a0ade492612faf3d84eeceaddc39a92 into a single commit called "start of deliteful".  But I tried that w/"git rebase -i" and it didn't work for me.

However, I learned from http://stackoverflow.com/questions/4515580/how-do-i-remove-the-old-history-from-a-git-repository that you can also truncate the history by:

```
$ echo b39692cc8a0ade492612faf3d84eeceaddc39a92 > .git/info/grafts
$ git filter-branch -f --tag-name-filter cat -- --all
```

So, if you want to erase all the pre-deliteful history, try the above commands, and then if everything looks ok:

```
$ git push --force
$ git push --tags --force
```
