### ISSUE TITLE
Cross Component: review all the CSS and document the tricky lines

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#392]
- [ ] list all the CSS lines that are cryptic/potentially problematic
- [ ] challenge authors to know the reasons for that cryptic/potentially problematic CSS
- [ ] change CSS that needs to be changed
- [ ] document CSS that needs to be documented
- [ ] review CSS for consistency in terms of setting things like font-size...

REMAINING WIDGETS: Checkbox, Combobox, RadioButton, Select (see #456), Switch, Toaster

**Comment by wkeese** [comment]
Closing this as we have no plans to continue with a global review.  May update individual widgets from time to time.
