### ISSUE TITLE
Components that do not need theming should not use the delite/theme! plugin

### ISSUE THREAD

**Issue by edurocher** [ibm-js/deliteful#399]
Currently, the ViewStack and SwapView components (maybe others? to check) do not have any theme-specific CSS, but they still have theme-specific CSS directories (which are all identical), and they load their CSS using the "delite/theme!..." plugin. It would be more efficient to have single CSS directory, and load the CSS using "requirejs-dplugins/css!...".

**Comment by cjolif** [comment]
As it seems there is no consensus and as we have higher priorities let's close this for now.
