### ISSUE TITLE
Develop a TreeViewer widget

### ISSUE THREAD

**Issue by dmandrioli** [ibm-js/deliteful#40]
**Design draft**
- layouts its children horizontally, creating "columns". All columns have the same width (using a LinearLayout with class=fill on all children).
- Number of columns is controlled by breakpoints in LESS file.
- Choice of breakpoints: reuse breakpoints of bootstrap ? http://getbootstrap.com/css/
- Rely on DisplayContainer architecture

**Comment by wkeese** [comment]
No plans to do this.
