### ISSUE TITLE
make HTML files in tests/functional load stand-alone

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#413]
Tests files like Switch.html cannot be loaded manually, because the parser only runs when the test file is launched via the Intern Switch.js script.

That makes it difficult to debug problems or run manual tests.   So I and @AdrianVasiliu suggest moving the `register.parse()` call from Switch.js to Switch.html, and likewise for the other test files that follow this pattern.

**Comment by wkeese** [comment]
@AdrianVasiliu, still planning to do this?   If not, I'll make the change.

**Comment by AdrianVasiliu** [comment]
Should be quick, I do it now.

**Comment by AdrianVasiliu** [comment]
Fixed via 273e543d58790e20af4e4b0443c44f0e6a89ae82.
The changes are in the tests of Button, Checkbox, SwapView, Switch. 
Remark: for Switch, Switch.html was calling the parser already, but Switch.js was also calling it - I removed the call from Switch.js.

**Comment by wkeese** [comment]
OK, thanks!
