### ISSUE TITLE
Part6DetailsView.md 404's

### ISSUE THREAD

**Issue by lbod** [ibm-js/deliteful#436]
I noticed there's 404s from https://github.com/ibm-js/deliteful/blob/f6a33a22ca37175a4948bf5bf7484dabbc39dce1/docs/tutorial/Part6DetailsView.md#run-the-demo

i.e. http://ibm-js.github.io/deliteful-tutorial/runnable/part6/index.html
for currencies.json, numbers.json etc, maybe just a build issue?

**Comment by cjolif** [comment]
@clmath, I'm wondering if there is not a root issue you might be missing here. Do you mean that there is not resilient way of scaling down the locale set from _outside_ the ecma402 code? If that is the case shouldn't the issue opened on ecma402?

**Comment by clmath** [comment]
> Do you mean that there is not resilient way of scaling down the locale set from outside the ecma402 code ?

No I don't think so except with a post install script or a build.

**Comment by wkeese** [comment]
No plans to do further work on this.
