### ISSUE TITLE
Inconsistency in tests resources

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#439]
Some tests/unit resources are in tests/unit/resources (like ScrollableShared...) some other (like a11yn.html) are in tests/resources. I would suggest to be consistent here and always use or or the other.

**Comment by AdrianVasiliu** [comment]
This situation exists in both delite (for which the examples given in the description hold) and deliteful.

In delite, tests/resources contains 2 files:
* a11y.html only used in a unit test => I suggest moving it to tests/unit/resources
* helloWorld.pdf only used in tests/test_bgIframe.html => this is one of the few .html test files still at the root of delite/tests, I suppose they are legacy tests that will either be removed or move to tests/functional? @wkeese? In the later case, creating a tests/functional/resources directory to move this pdf file might be the way to go.

In deliteful, tests/resources also contains 2 files:
* formAction.html: not used anywhere (at least according to a grep with the file name). Is it an outdated dijit legacy version of https://github.com/ibm-js/deliteful/blob/master/tests/functional/processForm.html? Any objection that it gets removed?
* loremIpsum.html: not used anywhere (at least according to a grep with the file name). => Any objection that it gets removed?

So for deliteful, if there's no objection, simply removing the entire tests/resources dir. would do the trick.

**Comment by cjolif** [comment]
yes sorry I was planning to create that one on delite but if there are similar issues in deliteful please go ahead.

**Comment by AdrianVasiliu** [comment]
Fixed for deliteful via 0decaa21518c99c7eeec461379c517baa513d2b8 .
For delite, you'll create a distinct issue?

**Comment by wkeese** [comment]
@AdrianVasiliu, your suggestions for delite made sense to me so I did them.  See links directly above this comment.  No need to create a separate issue.

**Comment by AdrianVasiliu** [comment]
@wkeese Fine. Now, there are a few other questionable files remaining at the root of delite/tests:

* place-clip.html and place-margin:html: outdated legacy DOH-based tests; either to be removed, or to be converted and moved to tests/functional?
* helpers.js: utilities only used by testes/functional/popup.html; unless it's likely to be also used in unit tests, to be  moved to tests/functional?
* boilerplate.js and boilerplateOnload.js: only used by functional tests and plate-clip.html + place-margin.html; if the later get removed or moved to tests/functional, the boileerplate stuff could also move to tests/functional.
* module.js and runTests.html: obsolete DOH stuff to be removed?
* video.swf: only used by the backgroundIFrame test now moved to tests/functional, so it could move to tests/functionnal/resources.

**Comment by cjolif** [comment]
> place-clip.html and place-margin:html: outdated legacy DOH-based tests; either to be removed, or to be converted and moved to tests/functional?

See ibm-js/delite#357 and I guess module goes with it...

**Comment by wkeese** [comment]
> Now, there are a few other questionable files remaining at the root of delite/tests:

OK, thanks, I'll deal with those two, probably following your suggestions (except for the place tests which, as Christophe mentioned, are covered by ibm-js/delite#357)
