### ISSUE TITLE
tests/module.js references place.html which does not exist

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#440]
Also I see delite/place is already tested in tests/unit, so does it make sense to keep tests/place-clip.html & tests/place-margin.html?

**Comment by wkeese** [comment]
732653a1b1484055c94c2adf6f3d6919df03f01f converted the old place.html test to Intern but not the other files.  I guess I should convert the other tests too.

**Comment by wkeese** [comment]
I removed the lline from module.js in ibm-js/delite@57951d24143fdc078bf320d11b7de02448706098, and filed ibm-js/delite#357.

Note that this is a delite issue, not deliteful, so the original ticket should have been against delite.
