### ISSUE TITLE
Switch: support textDir property

### ISSUE THREAD

**Issue by semion1956** [ibm-js/deliteful#450]
Support textDir for Switch labels (checkedLabel, uncheckedLabel) as well as title.

**Comment by cjolif** [comment]
see aso is #454 for other possible rtl issues with switch.

**Comment by semion1956** [comment]
This issue is about controlling text direction in the labels of Switch. #454 is about css, which doesn't cause rtl problem, but probably can be written better. As far as I can see, it isn't connected with current issue and should be solved separately.

**Comment by cjolif** [comment]
@semion1956 that's perfectly fine solving them separately just wanted to make to link both together in case one influence the other.
