### ISSUE TITLE
Tab & Accordion Container ? 

### ISSUE THREAD

**Issue by mc007** [ibm-js/deliteful#459]
Hi,
seems you made pretty good progress. Is a tab-container or accordion planned or scheduled yet? That's the only missing thing holding me back to switch from Dijit to delitful.
Thank you!
g

**Comment by cjolif** [comment]
Both are planned in #176 and #178. For tab you can see very early draft  here: https://github.com/cjolif/deliteful/commit/dffc6fb62158a3e212d0548a9a67eb775b5d56f3

**Comment by mc007** [comment]
awesome, thank you! will toy around with that, i hope its easier to extend the tab-button context menu than in dijit (adding more buttons beside 'close' (right-click) for 'split horizontal, etc...' ). And the other thing i had to introduce was a mixin called 'Mutatable' which converts the tab-container to a content-pane when it has only one tab (looks better) and vice versa: if addChild is called for a second tab: create tab-container automatically. i know that's outside of the normal, but just wanted to let you know. 

you can close this here if you like.

**Comment by cjolif** [comment]
closing this in favor of the pre-existing #176 and #178.
