### ISSUE TITLE
ToasterMessage: replace dimiss button character with an icon

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#460]
This follows up on @dmandrioli's comment: https://github.com/dmandrioli/deliteful/commit/c59e45d4cd7c50abc63ae2c65756a1003941e78e#commitcomment-9184497.
Once we have a way to use icons in our widgets, ToasterMessage should be updated.

**Comment by wkeese** [comment]
So the CSS is currently:

```
button.d-toaster-dismiss::before {
	content: "\00D7";
}
```

I think that's good enough.  It's essentially a font icon.
