### ISSUE TITLE
ProgressBar: formatExtraMsg() presumably backwards in RTL mode

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#466]
ProgressBar currently has this code:

```js
formatExtMsg: function (position, value, max) {
	return (this.isLeftToRight()) ? value + "/" + max : max + "/" + value;
},
```

That code is surely wrong.  It should just return `value + "/" + max` regardless of isLeftToRight().   The reason is that HTML has to be semantically correct (i.e. if you look at the raw HTML code it needs to make sense), so the raw HTML code needs to say 1/5 not 5/1.

If the fraction is displayed incorrectly in RTL mode, then you should use CSS etc. to make it print correctly.  dir=ltr hardcoded on that node, or style="direction: left", or even unicode directional characters.

Also, remember that it's not just about display.   There's also likely a screen reader issue.   But even if there isn't, the HTML needs to be semantically correct.

@semion1956?

**Comment by semion1956** [comment]
You are right, "val/max" should be displayed the same in any direction.
