### ISSUE TITLE
Bidi: tests are excluded because causing trouble, fix issues and re-enable theme

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#467]

**Comment by cjolif** [comment]
See also https://github.com/ibm-js/deliteful/pull/451#discussion_r23389604

**Comment by semion1956** [comment]
> Thinking more about this, I think the only viable solution will be to have bidi tests totally separated with its own intern config (inheriting from the standard one) and another grunt target to launch bidi tests (and maybe yet another one to run both bidi and non bidi).

Can it be the same grunt task with additional bidi subtasks (like local.bidi, local.android.bidi etc - not sure that I use the correct term), configured by intern.bidi, which sets bidi flag and refer to bidi suites only?

**Comment by clmath** [comment]
There is no such things as subtasks in grunt. The "local.android" or "local.ios" are just regular grunt task target and the "dot notation" is simply a convention. You could indeed create new "bidi" targets on the same model (like "local.bidi" etc.)
