### ISSUE TITLE
PageIndicator: viewstack property should be camel case

### ISSUE THREAD

**Issue by cjolif** [ibm-js/deliteful#470]
Shouldn't the viewstack property of PageIndicator be spelled viewStack?

(I'm asking because when designing #176 I created a viewStack property and realized after it was not consistent with PageIndicator)

**Comment by cjolif** [comment]
answering to myself, maybe this is better not to be camel case to be consistent with attribute naming where the case is not considererd.

**Comment by AdrianVasiliu** [comment]
I would share your initial feeling, in favor of "viewStack". I'm not sure why the consistency with camel-case naming of attributes would matter for this property in particular, while not holding in general, for all properties of all our custom elements (which can be set as attributes in markup)?

**Comment by cjolif** [comment]
@cc edurocher any feedback on why you picked non cased version?

**Comment by edurocher** [comment]
No particular reason that I can remember... Perhaps because of markup, yes, but Adrian is right that this is not a good reason. So i agree this should be changed.

**Comment by cjolif** [comment]
So I will change this and put an incompatibility statement in the release notes.
