### ISSUE TITLE
Switch: High-contrast mode should be supported

### ISSUE THREAD

**Issue by dmandrioli** [ibm-js/deliteful#477]
Rendering in high contrast mode (IE and FF) is not correct:
![image](https://cloud.githubusercontent.com/assets/1109677/5896740/ddd0bb70-a53a-11e4-9c96-95d2e76537b8.png)

**Comment by cjolif** [comment]
Not directly related but might worth be fixed with that:

* there is no standalone switch sample while there are for other form buttons?
* the checkbox sample has "switch samples" as title.
