### ISSUE TITLE
Button/ToggleButton:  interoperability with bootstrap

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#487]
- [ ] Can't "put things" inside button. Will be solved with https://github.com/ibm-js/deliteful/issues/290

- [ ] Can't be made look like a dropdown, AND a "split button dropdown" [see](  http://getbootstrap.com/components/#btn-dropdowns-split)
Also would be solved with https://github.com/ibm-js/deliteful/issues/290, or if there is a separate dropdown widget.
it should *ideally* support the variations offered by bootstrap (see [doc](http://getbootstrap.com/components/#btn-dropdowns-dropup))

Link to manual tests:  [Button](http://localhost:8080/bootstrap-deliteful/compiled/all-Button.html) [ToggleButton](http://localhost:8080/bootstrap-deliteful/compiled/all-ToggleButton.html)

**Comment by cjolif** [comment]
If all those issues would be fixed as part of #290 I suggest closing this in favor of #290...
