### ISSUE TITLE
RadioButton: interoperability with bootstrap.

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#489]
- [ ] When wrapped inside a class=radio element, like you would do it with a regular input[type=radio], deliteful/RadioButton shows two focus outlines.
  Hopefully, this will disappear with https://github.com/ibm-js/deliteful/issues/442#issuecomment-68891377

``` html
<div class="radio">
    <label>
        <d-radio-button></d-radio-button> Option 2
    </label>
</div>
```
- [ ] Outline color should follow the validation state style.

``` html
<div class="has-success radio">
    <label>
        <d-radio-button></d-radio-button> Option 2
    </label>
</div>
```
- [ ] alignment is broken: already filed in issue https://github.com/ibm-js/deliteful/issues/442

**Comment by cjolif** [comment]
This issue is mostyle about the 2nd point then. Other issues are dealt as part of #442.

**Comment by wkeese** [comment]
Closing this as we have no plans anymore to support interoperability with bootstrap.
