### ISSUE TITLE
Combobox: interoperability with bootstrap.

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#490]
Compared to bootstrap's select element
- [ ] Always the same width regardless of the width of its container. Not sure that's a problem but it's definitely not how an input field behaves in bootstrap.
- [ ] Insensitive to bootstrap sizing classes that apply to input fields.
- [ ] Some alignment issues in inline forms.

**Comment by AdrianVasiliu** [comment]
> Always the same width regardless of the width of its container. Not sure that's a problem but it's definitely not how an input field behaves in bootstrap.

It was an early design decision to not follow bootstrap on setting width: 100% by default. Could be revisited but only on phones (small screens - via multichannel policy), I would say.

> Insensitive to bootstrap sizing classes that apply to input fields.

Well, Combobox technically includes an input element but functionally is rather comparable with a select element (at least if autoFilter: false), so I wonder if it should be sensitive to boostrap sizing of input fields. Is a select element styled by bootstrap sensitive to that?

> Some alignment issues in inline forms.

Would be nice to have some details (screenshots and a code to reproduce).

**Comment by cjolif** [comment]
> It was an early design decision to not follow bootstrap on setting width: 100% by default. Could be revisited but only on phones (small screens - via multichannel policy), I would say.

Yes, there is a problem _only_ if that is not feasible to put it to 100%.

**Comment by tkrugg** [comment]
> Would be nice to have some details (screenshots and a code to reproduce)

Yes sure. I'm going to deploy the manual tests to gh-pages and post the link here. In the mean time, here are the screenshot and the code for 
>  - [ ] Some alignment issues in inline forms.

![image](https://cloud.githubusercontent.com/assets/2982512/5934481/6553c128-a6d0-11e4-8488-348fa1e6b5bb.png)

```html
	<form class="form-inline">
		<div class="form-group">
			<label class="sr-only" for="exampleInputEmail2">Email address</label>
			<input type="email" class="form-control" id="exampleInputEmail2" placeholder="Enter email">
		</div>
		<div class="form-group">
			<label class="sr-only" for="exampleInputPassword2">Password</label>
			<input type="password" class="form-control" id="exampleInputPassword2" placeholder="Password">
		</div>
			<label>
				<d-combobox>
				<d-list store="myStore2"></d-list>
				</d-combobox>
			</label>
			<button type="submit" class="btn btn-default">Sign in</button>
	</form>
```

As for:

**Comment by wkeese** [comment]
Closing this as we have no plans anymore to support interoperability with bootstrap.
