### ISSUE TITLE
Select: interoperability with bootstrap.

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#492]
- [ ] disabled mode doesn't look like bootstrap's (and the disabled state of other form elements)
- [ ] Bootstrap changes the cursor to `not-allowed` when hovering a disabled select. We might want the same with d-select
- [ ] focus outline color should follow validation state.
- [ ] regardless of the color, the focus outline is slightly different. 
  
  > As a general note, we should have one single way of highlighting the focused element. Ideally this should come from common classes every widget can reuse, not less variables/mixins as they tend to duplicate css unnecessarily.
  > For example, have a .d-input:focus that defines focus style, which can be used by combobox, select, checkbox, etc...
- [ ] Unlike bootstrap's select, it doesn't take all the space available in horizontally when put inside a container. 
- [ ] When applying .form-control class on <d-select>, you mess up the styling.
- [ ] Select does not adapt correctly to the different sizing options offered by bootstrap for `<select>`

All theses issues can be viewed in: http://tkrugg.github.io/bootstrap-deliteful/compiled/all-Select.html

**Comment by wkeese** [comment]
Closing this as we have no plans anymore to support interoperability with bootstrap.
