### ISSUE TITLE
StarRating: interoperability with bootstrap.

### ISSUE THREAD

**Issue by tkrugg** [ibm-js/deliteful#494]
- [x] <strike>The starts are not accurately centered inside their container box. It's not related to bootstrap only.</strike>
  ![image](https://cloud.githubusercontent.com/assets/2982512/5935827/58dd68b8-a6df-11e4-9032-6174d08a460e.png)
- [x] breaks bootstrap's inline forms (alignment and height of the element)
  ![image](https://cloud.githubusercontent.com/assets/2982512/5935885/b8a63e50-a6df-11e4-96c1-aa82048a2cb3.png)
- [x] Text in labels doesn't look aligned (will be solved in https://github.com/ibm-js/deliteful/pull/484)

[link to manual test](http://tkrugg.github.io/bootstrap-deliteful/compiled/all-starrating.html)

**Comment by cjolif** [comment]
> The stars are not accurately centered inside their container box. It's not related to bootstrap only.

This is the space needed to uncheck all starts. If you put allowZero=false on it the problem should disappear.

**Comment by tkrugg** [comment]
oh, ok. I wasn't aware of that feature. I'll check that off.

**Comment by buberdds** [comment]
Hey, I looked at this and pushed a PR to bootstrap-deliteful. On this demo site ("link to manual test") you are missing vertical-align: middle; property for .d-star-rating selector too.

This property is defined already in StarRating_template.less line 8, so maybe it's just a matter of a build.

**Comment by wkeese** [comment]
Closing this as we have no plans anymore to support interoperability with bootstrap.
