### ISSUE TITLE
LESS variables naming consistency

### ISSUE THREAD

**Issue by dmandrioli** [ibm-js/deliteful#496]
As discussed here https://github.com/ibm-js/deliteful/pull/491/files#r23679293.
- [ ] Rename variables. Pattern: @d-switch-width, @d-sidepane-animation-duration and so on
- [ ] Ensure variables definition are in each widget theme default less file
- [ ] Factorize variables if possible

**Comment by cjolif** [comment]
and maybe factorize some of them if that makes sense?

**Comment by wkeese** [comment]
No plans to fix this.
