### ISSUE TITLE
List: allow selection using keyboard regardless of the target of the keyboard event

### ISSUE THREAD

**Issue by AdrianVasiliu** [ibm-js/deliteful#500]
List handles SPACE key events via `_spaceKeydownHandler` which passes the key event to List.handleSelection. Now, this method relies exclusively on the target of the key event: if evt.target is not enclosed by an item renderer, it does nothing (see https://github.com/ibm-js/deliteful/blob/0.6.0-alpha/list/List.js#L464-471). 

This is problematic in use-cases where the List navigation is controled with key events on an element outside the List, as in the use-case of List inside the popup of Combobox. Hence, List.handleSelection could rely on the `navigatedDescendant` property for determining the element to select/deselect. However, this deserves care, at least because handleSelection is overridden in PageableList where it deals also with the prev/next page loaders elements... (https://github.com/ibm-js/deliteful/blob/0.6.0-alpha/list/PageableList.js#L771-781).

**Comment by AdrianVasiliu** [comment]
Originates from @wkeese comment: https://github.com/ibm-js/deliteful/pull/497#commitcomment-9489009.

**Comment by wkeese** [comment]
It's still using `event.target` but I guess this isn't an issue anymore since 6cc397814f720d396d9242d6276885015f270dfb.
