### ISSUE TITLE
List: create a sample that illustrates transitions from a list initiated by a click (or keyboard action) on a list item

### ISSUE THREAD

**Issue by sbrunot** [ibm-js/deliteful#51]
A sample should be added that demonstrate a list of items that, clicked / tapped / receiving key SPACE or ENTER performs a transition to another view (a different view for each list item).

EDIT (CJ): Only the accessibility part seems to be incomplete on that one (last comment from @wkeese all the other items are completed)

**Comment by wkeese** [comment]
Closing this since we have no current plans to implement it.
