### ISSUE TITLE
preserve custom markup in form elements?

### ISSUE THREAD

**Issue by mc007** [ibm-js/deliteful#514]
Hi,
Is there a way that the parser doesn't wipes out my custom markup within d-button and others? 

that's the markup:

``` html
<button is="d-button" label="Default button" onclick="alert(this.label + ' clicked.');">
        <xblox data-dojo-type="xblox/RunScript" blockId="aeaca388-5782-f624-54f0-900fec9b686c" script="On Key" block="root://min.xblox" targetEvent="onclick"></xblox>
</button>
```

after parsing, the 'xblox' element is gone and the entire Dom-Structure changed to 'spans' too of course. I know thats quite an edge case, but would it be possible? 

thank you,

this is part of the Maqetta adaption for deliteful and I'd like to place those tags in the markup to avoid messing with ids and relations.

**Comment by cjolif** [comment]
If you issue is just for button #290 should solve it. (FYI the problem is not with the "parser" but the button implementation itself).

**Comment by mc007** [comment]
I just realized that this tag(pure data, not an registered and rendered HTML5 element) needs to go in any widget/container (renamed the issue).

In Dijit (same problem) this node gets wiped out in dijit/_Widget::create as part of dijit/_TemplatedMixin which deletes the srcNodeRef so that the tag(a child of it) looses its parentNode and therefore I can't link this tag to the surround target widget anymore(orphan, ie: parentNode gone). Not quite sure in which direction sub-elements get parsed, ie: inside -> out or vice versa, but yes. thats pretty much the problem. (Later on, in the xblox/RunScript widget implementation, I just want to link it to the 'button')

Possibly this idea is an dead end (remove deps to an 'id') or its not supported, yet. Can i fix this somewhere ? 

Thank you, again.

**Comment by wkeese** [comment]
The button issue is a duplicate of #290.

> In Dijit (same problem) this node gets wiped out in dijit/_Widget::create as part of dijit/_TemplatedMixin 

Only if your widget extends dijit/_TemplatedMixin.   Likewise with delite.

> Is there a way that the parser doesn't wipes out my custom markup within d-button and others?

As @cjolif mentioned, the parser doesn't wipe out anything.

If you have a simple behavioral widget the `<xblox>` subnode will be left as is, and there's no problem.

If you have a widget with a template, like `<d-button>`, then the widget should extend delite/Container, and define containerNode.

**Comment by mc007** [comment]
Thank you both, and sure, its not directly the parser :-)
I checked other widgets, and its seems all fine.
guenter
