### ISSUE TITLE
CSS should always use d-rtl class, not dir="rtl"

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#518]
Currently Switch_template.less and Combobox_template.less have CSS selectors using `[dir="rtl"]` when they should use `.d-rtl`.  The former doesn't work when `dir=rtl` is set on `<body>`.

But see also #454 and #517.

**Comment by AdrianVasiliu** [comment]
More exactly, Switch and Combobox have CSS selectors for `[dir="rtl"]` in addition (not instead) of `.d-rtl`. Just to be sure, before going for the removal (in both Combobox and Switch) of the `[dir="rtl"]` selector, @wkeese please confirm there's no supported browser where setting the `dir` attribute may not trigger refreshRendering(), thus may not set the `d-rtl` class.

**Comment by wkeese** [comment]
Right, I confirm.   (If that does happen it's a bug.)

**Comment by AdrianVasiliu** [comment]
Pushed via c3b8f8fe42ad4951dba4680add88d3316258fa8b.
