### ISSUE TITLE
get selected value in Select/Combobox.on('change',function(e)}{...}) ? 

### ISSUE THREAD

**Issue by mc007** [ibm-js/deliteful#520]
Hi,
when fired i I can find my new selection only in e.currentTarget.value or in e.currentTarget.list.selectedItem. 
Is this on purpose or is there an API to resolve this from the event? 
thank you.

**Comment by wkeese** [comment]
>  I can find my new selection in e.currentTarget.value

OK, great.   What's the problem?

**Comment by mc007** [comment]
ok, if that is the official way, then fine. I was not really sure since dijit gave me the value in the calback more directly. 
thank you,
guenter

**Comment by wkeese** [comment]
You are right that dijit's onChange() method got passed the new value directly, but with delite, everything is Event objects.  This is to match native DOM element behavior.
