### ISSUE TITLE
Different global theme folder?

### ISSUE THREAD

**Issue by mc007** [ibm-js/deliteful#524]
I started adding stock Bootstrap themes to my Deliteful fork (https://github.com/mc007/deliteful) for the themes downloadable for free (MIT) from [here](http://bootswatch.com/). I added the 'superhero' theme to all widgets in my fork (also for the demos). This theme includes some fixes as well. 

The good news: deliteful seems to work out of the box with those themes! You can see it [here](http://www.pearls-media.com:89/client/src/lib/ibm-js/deliteful/samples/Combobox.html) in action :-)

There are just a few [tiny issues](https://github.com/mc007/deliteful/blob/master/ThemeIssues.md) with dark themes. 

The problem: I'd like to shift the theme folder globally which is no problem for loading the global.css:
"delite/theme!delite/themes/../../../superhero/global.css", but the widget's theme requires remain unaffected from this. 

Ideally it would be great to pass to the require config a relative or absolute url to the theme folder, so all the widget's theme files can be outside of the deliteful folder. 

If this is not an issue to, please close it. We will go with adding more stock themes to the fork. The next candidate apart from the 'bootswatch' themes is a 'transparent' one: http://wrapbootstrap.com/preview/WB0T41TX4 ([Complete source code, worth to check it since its top notch and very complete, using handlebars as well](https://github.com/mc007/bootrap-light-blue-admin-theme)) which comes in SASS format, also involving some other but related problems with the current widget theme loader I guess.

**Comment by wkeese** [comment]
Hi Günter,

Cool, you are adding new themes.   Being able to have themes outside of the deliteful/ project is definitely an issue, but the it's already covered by #457.  That ticket mentions modifying an existing theme, but I think it covers creating completely new themes too.

BTW, you titled this issue as:

> Different global theme folder

But I think really you just want to redirect certain themes to different folders, while leaving holodark etc. where they are?

**Comment by mc007** [comment]
Hi,
ok then, its on the way.

Yes, the entire theme could be outside of deliteful, primarily avoiding that I need to fork it. 

Not sure yet how this goes at build time but it shouldn't be a problem but his could do the job:

"delite/theme!./Button/themes/{{theme}}/Button.css"

becomes:

"delite/theme!{{themeRoot}}./Button/themes/{{theme}}/Button.css"

where themeRoot is set '' if not set. I see the ideas in #457:

I'd prefer variable substitution in general (all over the place), I did this for my projects and its pretty powerful, no idea how you do this on require-urls but I guess thats no real biggy. So instead of 

return css.id + "!" + path.replace(/{{theme}}/, load.getTheme());

this could be more flexible: 

return this.resolve(path,config.variables,config.defaults) // or similar :-)

And even if that is solved that way, I am not really convinced this is standing for long. Instead of require directives, its better to make a variable of the widget, only then you can override it by server side mixins on widgets (i do this a lot too). 

here a simple but powerful variable replacer : https://github.com/mc007/xide-js/blob/master/utils/StringUtils.js#L307

amen, and thank you for the support!

**Comment by wkeese** [comment]
> "delite/theme!{{themeRoot}}./Button/themes/{{theme}}/Button.css"

But remember, as I said above, you really just want to redirect certain themes to different folders, while leaving holodark etc. where it is.   Therefore {{themeRoot}} doesn't really make sense.

> I'd prefer variable substitution in general (all over the place)

Sure, makes sense.   Note that {{theme}} is special though because delite/theme! figures out the replacement value automatically.

> And even if that is solved that way, I am not really convinced this is standing for long. Instead of require directives, its better to make it a variable of the widget, only then you can override it by server side mixins on widgets (i do this a lot too).

Hmm, what do you mean by "it" exactly?

**Comment by mc007** [comment]
Hi,
sorry, didn't want to bug too much on this. Do as you like but how its done right now can't stay like that.

About 'leaving holodark': not sure i understand this right. Sure it can stay where it is; the problem 
is: I don't know how to redirect the theme variable (global.css , Button.css) to somewhere outside of the deliteful/folder folder. Because if you set {{theme}} to '../../../myThemes/superhero' (awful) then I get this 404's:
http://127.0.0.1/projects/x4mm/Code/client/src/lib/myThemes/superhero/common.css"
http://127.0.0.1/projects/x4mm/Code/client/src/lib/ibm-js/myThemes/superhero/Button.css"
http://127.0.0.1/projects/x4mm/Code/client/src/lib/ibm-js/deliteful/myThemes/superhero/List.css"
http://127.0.0.1/projects/x4mm/Code/client/src/lib/ibm-js/myThemes/superhero/ProgressIndicator.css"

where deliteful/delite sits in src/lib/ibm-js/

and if you set it to: 'http://cdn.themes.com/myThemes/superhero':

I get this 404's

http://127.0.0.1/projects/x4mm/Code/client/src/lib/delite/themes/http://cdn.themes.com/myThemes/superhero/common.css"
http://127.0.0.1/projects/x4mm/Code/client/src/lib/deliteful/list/List/themes/http://cdn.themes.com/myThemes/superhero/List.css"

Sure, I could place those files there and make deliteful happy, but you see, this is a dead end. The resulting and needed folder-structure is pretty annoying. That's why 2 variables:

themeRoot: absolute or relative
theme: absolute or relative

and actually to make it really right, add a dynamic variable for 'widget' to avoid things like '../Button.css'

that makes the final theme path almost to a pattern:

"delite/theme!{{themeRoot}}/{{widget}}/themes/{{theme}}/{{widget}}.css"

then you could put this even in the widget base class and remove it from all widgets. I am aware how convenient such require-css directives are to you, but as in dGrid which used xStyle in the same way,  
its was pretty annoying that this will be pulled as require-js/css plugin: it can stop the entire application if you didn't place that files on the server. And worst, as developer/user you have little options to apply your own resource loading techniques. 

And at this point, we are at your question what it is meant by 'it':  Assuming you solved the widget's theme path problem, in one way or another, pulling the the widget's theme files through a non-editable way (the require-path/url) makes it hard to pass the theme-path as constructor argument. There might be cases (no, that are common cases, think of CMS or Blogs) where you want to run different themes in the same application. 

However, I think i will move to "delite/theme!{{themeRoot}}/{{widget}}/themes/{{theme}}/{{widget}}.css" for now, and remove it from the widgets and make it as variable instead of a require directive. The same should happen with the handlebar templates.

thank you, again!
please take it feedback, i am going to use deliteful in 3 types of applications IDE, lib, component. All require different techniques about themes and resources. 

g

**Comment by mc007** [comment]
there is also https://github.com/jrburke/requirejs/wiki/Fine-grained-URL-control. this could assist the theme url re-directs.

**Comment by wkeese** [comment]
What do you think would be the ideal directory structure to support deliteful's built in themes, but also the themes that you are working on?

**Comment by mc007** [comment]
the one you have is already nice and ok, 
sure, i'd prefer one complete folder per widget: Button/Button.js | themes | templates | nls, but maybe later.

And using something like this as pattern: {{themeRoot}}/{{widget}}/themes/{{theme}}/{{widget}}.css

could free it from a fixed folder-structure, in conjunction with an additional require.load hook (as last instance) all cases I can think of are pretty much covered. At build-time, you'll only need to resolve those variables to absolute paths. 

addons -): there is since long another variable in my system: run-time-configuration: 'release' and 'debug', 'build' and 'release-debug'. I usually switch resource locations/variables through url with this as well. So if you do something like a user-variable controlled resource resolver, then define those variables per 'config'. 

ok, sorry. it doesn't answer your question right away, but I think leaving it up to a 'pattern' might solve more.

**Comment by mc007** [comment]
ok, for me its done. i made an extra repo: https://github.com/mc007/xdelite for all new themes but also the patchs for some delite stuff.

i extended (all as require-js map ) theme in xdelite/theme: https://github.com/mc007/xdelite/blob/master/theme.js#L109

so i can pass all variables in require.config: 

'xdelite/theme':{
                        theme:'superhero',
                        variables:{
                            theme:'superhero',
                            themeRoot:'xdelite/themes/'
                        }
                    }

and the resulting patches in all widgets: 
"delite/theme!{{themeRoot}}/{{theme}}/Switch/Switch.css"

simply but works ok enough for now. I'd love to get rid of the url string. Possibly through another 
require-js plugin which pulls the variable: "delite/variable!{{widgetThemeUrl}}" so I have access to module.id and complete it over the config. 

case solved :-)

**Comment by wkeese** [comment]
OK, glad it's working for you.

I think you're really missing my point about why {{themeRoot}} doesn't make sense.   Try updating your test case so it uses your "superhero" theme on desktop but uses deliteful's iOS theme on iOS.

> pass the theme-path as constructor argument.

It's an interesting idea but I don't think it's practical for us.  One complication is that the widget instances would likely be instantiated before the CSS was downloaded.  Another complication is that we are only designed to have one theme per page, not to have different themes for different widget instances.  This is an intentional decision, not an oversight.

> return this.resolve(path,config.variables,config.defaults) // or similar :-)

Sure, it's simple to let the app specify a custom function to remap CSS file paths.  I just think it would be nice to [also] have a simpler API to specify a remapping.

**Comment by mc007** [comment]
ok then. 
themeRoot (can be ''  too) can be fixed for this (theme map). and, i pretty much doubt that we' use deliteful built-in themes (as for dijit or dojox). 

The directory pattern idea for the theme require url is still looking the best way out to me, I just don't know how to modify that url for module.id (to complete for 'Button'.css) yet without using require.load hook. Require-js seems also inflexible in such things, 'has?...' is nice but really not enough. 

And about constructor args: i stopped trying this because register doesn't work async(for same reasons...sure). So possibly i will extend register#upgrade or similar to get this feature, to make sure its all at place when parse() is called. How about appending registry for a Dfd?

Different themes: too bad, I guess nothing is prefixed then, np. :-)

ok, thanks again, don't bother too much. i guess those things will get sorted anyways.

**Comment by mc007** [comment]
after toying today with a SASS based bootstrap theme (the transparent theme i showed you) but also adding multi-theme support to xdelite/themes/*,

this is the final directory structure for a theme: https://github.com/mc007/xdelite/tree/master/themes/superhero

its flat, straight and no exorbitant paths, and stands the most scenarios i can think of.
