### ISSUE TITLE
theming: how to change css prefixing/class-names for widgets ? 

### ISSUE THREAD

**Issue by mc007** [ibm-js/deliteful#525]
Simply close or ignore this issue if its out of scope to you.

When adding other stock themes (bootstrap based), using different css prefixing or pre-processors,
I got only this options:

1. rewrite the entire theme for the deliteful CSS prefixing (ie: 'btn' becomes 'd-button' ) : a No-Go of course. 

2. adjust all widgets (baseClass) and related files (samples/tests) manually for replacing d-button to the theme's css prefix, ie: all d-button become 'btn' : a No-Go as well.

3. The last option is to do the replace at 'register' level. That seems the only place to do that and its a realistic option:

I could manage to replace the widget's baseClass in register.register, but I can't get it work for 
the additional classes as 'd-button-success'. I tried to replace this in register.upgrade with an awful hack, but it doesn't seem reliable; also it seems the wrong place since the widget is already rendered and I am triggering a second rendering in browser for manipulating the widget's css clases. 

Do you know the right place or way to patch this? I am aware that some widgets need indeed extra efforts but with the most, a generic solution could be applied. 

thank you!

**Comment by wkeese** [comment]
Sorry, I have no idea what you mean by "css prefixing".

You can easily change the class names by changing the `baseClass` property.

**Comment by mc007** [comment]
yeah, but thats not all, what for 'd-warning' ?

**Comment by mc007** [comment]
because, the pattern isn't just 'd-'

**Comment by wkeese** [comment]
> yeah, but thats not all, what for 'd-warning' ?

What about it?

**Comment by mc007** [comment]
ok, got it, sample files need to be dynamic as well; handlebars then too.

**Comment by tkrugg** [comment]
This is not directly related to the issue but only regarding interoperability with bootstrap: you *should* be able to use on deliteful widgets, the sames classes you would on a their bootstrap equivalent. For example the d-button should support `btn-{primary,warning,...}`. In fact the `d-button-{primary,warning,...}` classes you can see in the d-button stylesheet are pretty useless if you ask me. The way I see this, if you want to create a deliteful app with the bootstrap theme, you'll need to ship a couple of stylesheets from bootstrap to get a consistent look (grid, forms, typography, ...  aren't shipped with delite).

In the very case of d-button, I can affirm this works just as expected ([proof](http://tkrugg.github.io/bootstrap-deliteful/compiled/all-Button.html)):
```html
<button is="d-button" class="btn-warning">Click</button>
```
For other widgets that have a bootstrap equivalent, we are working in that direction: we have a bunch of issues opened for it.

**Comment by mc007** [comment]
Hi,
@tkrugg 
I will try that!  Your page is great help for adding themes. I will use it definitely, thanks for that. 

Unfortunately I can't really wait for anything, so I will keep moving with my fork(s). There are too many issues for me in the way to use delite/deliteful directly nor to extend it for new themes (many and non-less based): https://github.com/mc007/xdelite/blob/master/Themes.md.

That are the major show-stoppers to me right now: 
1. no multi-theme support
2. theme files are fetched through require, that also impacts my build-tasks a lot
3. no support for a global theme directory outside of the deliteful/delite folder
4. changing base CSS prefix requires too many changes and hacks

I got the most of it fixed or done (except 4.), in the forks. As soon I've got the first non-less based bootstrap theme from the stock-market full running, I'll let you know. Things got more clear then to me too. 

thanks,

guenter

**Comment by mc007** [comment]
@tkrugg sorry, I can't find the source to your 'proof' link. Could you please tell where it get it? Thank you!
g

**Comment by tkrugg** [comment]
sure, the project is here: https://github.com/tkrugg/bootstrap-deliteful
The page ([source](https://github.com/tkrugg/bootstrap-deliteful/blob/master/compiled/all-Button.html)) you're seeing is featuring two iframes which are: [bootstrap--Button.html](https://github.com/tkrugg/bootstrap-deliteful/blob/master/compiled/bootstrap--Button.html) and  [deliteful--Button.html](https://github.com/tkrugg/bootstrap-deliteful/blob/master/compiled/deliteful--Button.html)

**Comment by gbaumgart** [comment]
Hi,
is there any plan to remove all that css requires from the modules one day? 
thanks a lot.

**Comment by wkeese** [comment]
We don't have a plan for that... if you don't want the default CSS you could just change the theme to "mytheme" instead of "bootstrap", and then make your own CSS files.   That approach is admittedly a bit of a hassle because you would need to put your custom CSS files into the deliteful directory, or some trickery to redirect the CSS requests to a different directory.

The reason modules require their CSS, besides convenience, is to avoid race conditions rendering the widget before its CSS has loaded.   Although that may no longer be an issue, since deliteful does its sizing in CSS rather than in javascript.

**Comment by gbaumgart** [comment]
I understand, no problem.
thanks again
