### ISSUE TITLE
Add a note on the CSS Architecture of Elements.

### ISSUE THREAD

**Issue by gaurav21r** [ibm-js/deliteful#528]
My team and I have been long term users of Dojo 1.x and also frequent contributors. One of the many things I appreciate about this project is how its leveraging **modern standards**.

Things like **flexbox** and **CSSGrids** offer a clean way for us to build our custom widget infrastructure as opposed to adding event listeners and changing CSS directly with JS. Our Front end engineers have an extremely tough time going through a styling issue whether it is in the HTML template, the JS Class for the Widget or the CSS. Extending claro is a nightmare.

Although this project defers to modern CSS for styling (eg: using the `:disabled` pseudo selector rather than the JS class adding a CSS class and using semantic elements like `<select>`, `<button>` I still see some pieces of code where CSS is getting injected by JS. This is purposely avoided in frameworks like Bootstrap (although I know delite is architecturally different and assumes JS to be the core).

Can we have deliteful in a way that **the widget classes only change the CSS class of the widget and nothing more?**

Perhaps a discussion and an architectural note in the `docs/` regarding this?

**Comment by cjolif** [comment]
Thanks for the input.

Actually we already have a rule that should mostly cover what you are saying. if you look at https://github.com/ibm-js/sdk/blob/master/GUIDELINES.md

"JavaScript code SHOULD NOT hard code style but rely on stylesheets"

As you have seen this is not always true (thus the SHOULD NOT and not MUST NOT). Sometimes for good reasons (this is structuring CSS) sometimes for bad reasons. Maybe you could list the occurrences you found and we would review them as time allows to see if they can be changed.

**Comment by gaurav21r** [comment]
@cjolif Thanks! I will go through this and let you know. Can  you please keep this open and I can list individual cases here?

**Comment by cjolif** [comment]
No news, closing. But feel free to put more info here, in which case I'll re-open.
