### ISSUE TITLE
StarRating test failing with delite 0.7 beta

### ISSUE THREAD

**Issue by edchat** [ibm-js/deliteful#531]
There has been a lot of discussion about this via email.  I will summarize here:
This test was failing:
*FAILED Test  'main - StarRating tests - form values' on internet explorer 10 on WINDOWS:
AssertionError: expected [ 'star4', '4', 'star5', '5' ] to deeply equal [ Array(8) ]
The problem was related to StarRating createdCallback: register.after()
Once createdCallback was updated to call super instead that test passed, but this test began failing:
>> *FAILED Test  'main -  - form back button' on internet explorer 11 on WINDOWS:
AssertionError: aria-valuenow: expected '1' to equal '7'

Bill suggested that the code in createdCallback: dcl.after(...) should be moved to postRender: ...
I tried that, and the first test is still passing, but the second test is still failing, this is what I am seeing:

StarRating.postRender, is getting the correct value (7) and is setting this.value = this.valueNode.value. 
But in FormWidget.refreshRendering it is setting valueNode.value from this.value and for some reason this.value is 1, so it is causing the new test failure.

>> *FAILED Test  'main -  - form back button' on internet explorer 11 on WINDOWS:
AssertionError: aria-valuenow: expected '1' to equal '7'

**Comment by edchat** [comment]
So the value is being reset to 1 in CustomElement.createdCallback after() because _parsedAttributes includes value: 1.  So that is why it was using advise after in StarRating.createdCallback, so that it would happen after this.

**Comment by edchat** [comment]
In StarRating.postRender, when setting this.value from the input value (if a value is set) I can add code to also set the value attribute to the input value like this:
```javascript
					this.value = this.valueNode.value;
					this._parsedAttributes.forEach(function (pa) {
						if (pa.prop === "value") {
							pa.value = this.value;  // set the value attribute to avoid this.value being replaced
						}
					}, this);
```
With this change all of the StarRating tests are passing.
@wkeese do you have any better suggestions?

**Comment by wkeese** [comment]
I was thinking along these lines, although probably you can just do

```
this._parsedAttributes.value = this.valueNode.value
```

There shouldn't be any "change" event caused by specifying an initial value in a nested `<input>`.  I'm guessing the old code caused a change event?

**Comment by wkeese** [comment]
PS: On second thought I guess there's probably no problem with change events.  But maybe a slightly cleaner solution than the putting the above code in postRender() is to override _mapAttributes().  The notifyCurrentValue() calls should still be in postRender(), like other widgets.

**Comment by edchat** [comment]
Thanks @wkeese maybe I am missing something, but is seems simpler and cleaner to just add the code to postRender(), than to override the private _mapAttributes(). 
I was able to get it to work by overriding _mapAttributes, I assume you wanted to move the code there in order to be able to set the value from the input after dealing with the attributes (via a call to super)?  If that is the case I still had to update the value attribute. 

In either case I had to use the this._parsedAttributes.forEach instead of the one liner you suggested, the _parsedAttributes is an array of objects with a "prop" and "value", so I could not just reference value.

**Comment by wkeese** [comment]
>  maybe I am missing something, but is seems simpler and cleaner to just add the code to postRender(), than to override the private _mapAttributes()

The reason I mentioned _mapAttributes() is because that's the method that's in charge of getting the original attribute settings for the widget, and a nested `<input value=...>` seems pretty similar to a `value=...` attribute on the root node.

It's true that `_mapAttributes()` is marked as private, but so is `_parsedAttributes`.  I thought it would make sense to change `mapAttributes()` to a protected method after the dust settles.

> In either case I had to use the this._parsedAttributes.forEach instead of the one liner you suggested, the _parsedAttributes is an array of objects with a "prop" and "value", so I could not just reference value.

Oh OK, I forgot that it's an array like that.  So, what you said is essentially true, although technically you don't need to access _parsedAttributes or use forEach().  You could presumably do [something like]:

```js
_mapAttributes: dcl.superCall(function(sup) {
   return function () {
        var res = sup.call(this);
        if (this.valueNode) {
              var obj = res.find(function(x) { return x.prop === "value"; });
              if (obj) { obj.value = this.valueNode.value }
              else { res.push({prop: "value", value: this.valueNode.value}) }
        }
        return res;
   };
})
```

The code snippet you did seems strange because you are setting this.value in postRender(), whereas all the other initial property values are setting at the end of createdCallback().   I feel like that inconsistency will lead to some problems but not sure exactly what.

**Comment by cjolif** [comment]
I suspect other widget inheriting for FormValueWidget will face similar issues as soon as they want to expose the  value of the valueNode as a property? Do we expect our users creating their own widget to also override mapAttributes? Maybe it would make sense if FormValueWidget would do that for them?

**Comment by edchat** [comment]
This code is also adding an input field if there is not one already, and I am not sure that would be something needed for all FormValueWidgets.

**Comment by edchat** [comment]
Unless someone objects, I would like to push this update, and close this out, if we decide to make the change in FormValueWidget or make some additional change to this I will reopen this issue.  
Thanks.

**Comment by edchat** [comment]
Merged https://github.com/ibm-js/deliteful/commit/69ff7aaae2363c4e31e2b162022ce87e967809a2

**Comment by wkeese** [comment]
Sure.   I filed ibm-js/delite#394 for possibly adding it to delite in the future.
