### ISSUE TITLE
Slider test failing with delite 0.7 beta

### ISSUE THREAD

**Issue by edchat** [ibm-js/deliteful#532]
@wkeese I am also having problems with Slider, and getting the value set correctly, when using a range, you can see this with the Slider.html sample, or for a simpler case, when creating a Slider programmatically with code like this:
```
			var slider = new Slider({
				id: "sliderWidget",
				value: "25,75"
			}).placeAt("sliderWidget_ph");
```
The value"25,75" is not being set correctly, previously the value was set before the first call to computeProperties, but now the value is "" until much later.  
FYI, attachedCallback is not called until much later now.

**Comment by wkeese** [comment]
> The value"25,75" is not being set correctly, previously the value was set before the first call to computeProperties, but now the value is "" until much later.

With the current delite, user code like `new Slider({value: "25,75"})` is executed identically to:

```js
var slider = new Slider();  // causes call to computeProperties() and refreshRendering() with default value
slider.value = "25,75";
slider.deliver(); // causes call to computeProperties() and refreshRendering() with value="25, 75"
```

Maybe that should change because it's inefficient, but I don't see why it's breaking anything.

> FYI, attachedCallback is not called until much later now.

Right, it's expected for computeProperties() and refreshRendering() to get called before attachedCallback().

**Comment by wkeese** [comment]
I could probably move the `this.deliver()` call from CustomElement#createdCallback() to CustomElement#attachedCallback().   I'll try that tomorrow.

Still, from your description, it sounds like there's a pre-existing bug in Slider where something like this never worked?

```
var slider = register.createElement("d-slider");
document.appendChild(slider);
slider.attachedCallback();
slider.value = "25, 75";
```

**Comment by edchat** [comment]
I suspect you may be right, the Slider tests call slider.attachedCallback(); after setting the value.

**Comment by edchat** [comment]
@wkeese said "I could probably move the this.deliver() call from CustomElement#createdCallback() to CustomElement#attachedCallback()."
Making that change did solve the problem in Slider, but I don't know if it would cause problems somewhere else.

**Comment by wkeese** [comment]
OK, I filed #535 for the pre-existing Slider problem.   The change to when deliver() is called doesn't seem to break anything else (at least in delite), so I will check it in.
