### ISSUE TITLE
ResponsiveColumns is not resetting screenClass when the breakpoints are changed.

### ISSUE THREAD

**Issue by edchat** [ibm-js/deliteful#534]
Once screenClass is set it will not be updated, and this can cause problems.  You can see a test failure if the screen size happens to be between 901 - 1023, which would initially make screenClass=medium, but after setting the breakpoints with breakpoints = "{'small': '500px', 'medium': '900px', 'large': ''}" it will expect screenClass to be large.
The problem is here: https://github.com/ibm-js/deliteful/blob/master/ResponsiveColumns.js#L186

**Comment by edchat** [comment]
Fixed.

**Comment by cjolif** [comment]
thanks a lot @edchat

**Comment by edchat** [comment]
Well travis still had a failure for ResponsiveColunms, but it is not one that I am able to reproduce on Saucelabs. 
>> *FAILED Test 'main - ResponsiveColumns - Media Query Test' on internet explorer 10 on WINDOWS:
AssertionError: Wrong percent size: expected false to be true
