### ISSUE TITLE
SidePane not initialising correctly when included in template

### ISSUE THREAD

**Issue by martinfitzg** [ibm-js/deliteful#536]
Hello all,

Doing a few hello worlds here and I've put the "d-side-pane" along with a few others (see screen shot below) into a template in a custom widget.  All worked ok when it was all stand alone in a html page but putting it into the template caused issues.

In the file  ./deliteful/SidePane.js first line in the refreshRendering function there is 

<code>
this.parentNode.style.overflow = "hidden";
</code>

It errors out here with the parentNode been null, if I change that to 

<code>
if(this.parentNode != null){
this.parentNode.style.overflow = "hidden";
}
</code>

It works correctly, but I'm not 100% sure what the effects of that down the line are....

![capture](https://cloud.githubusercontent.com/assets/5325187/6882111/c062f932-d572-11e4-9b6e-8b3da87cf934.PNG)

**Comment by wkeese** [comment]
I fixed this earlier this month in c042dfb87bf495f7f7a8d1e1788a5132e5785078.
