### ISSUE TITLE
d-select selectionMode  multiple inconsistent across browser 

### ISSUE THREAD

**Issue by martinfitzg** [ibm-js/deliteful#537]
Hello all,
            Have a "d-select" on page with it set to multiple.  Running this on andriod 5.0.2 in Chrome version 41.X and HTC browser 7.0.25

In Chrome the d-select  says "0 selected" and when 3 items have been selected it says "3 selected" 

In them 'more' stock browser it displays the first item on the lists name and when 3 items have been selected it  highlights the first item (displaying it's label) with a seemingly random color.

To me both should function as it does in chrome

Tried this in chrome / ie / ff on the desktop and works as one would expect.  All the though the scrollbars in IE 11 look a little "out of place" but that's more of a browser issue I guess.

**Comment by AdrianVasiliu** [comment]
With which release? Or is it with the current master?
Might not matter but did you test on a real device? (which one?) Or was it on a simulator?
Yes, the scrollbars in IE11 (as in all browsers) are up to the browser's rendering of the underlying `<select>`.

**Comment by AdrianVasiliu** [comment]
Although I couldn't check (our Android 5.x test devices are Nexus, where there is no stock browser), I suspect what you see is nothing else than the different rendering of HTML `<select multiple>` in stock browser vs. Chrome. You could try with a pure HTML file, you should see the same difference. Given that deliteful/Select leverages HTML `<select>`, this seems unavoidable. That is, I think this falls into "browser issue".

Note that deliteful/Combobox is a complementary widget, which does not leverage the "native" select. For a comparison (pros/cons of each), see my blog post here: http://ibm-js.github.io/2014/11/03/combobox-select.html.

**Comment by martinfitzg** [comment]
With delightful version 0.6.x.  Ran it on a HTC one m7 running andriod 5.0.2  

There is different behaviour runing a pure html file with multiple select in it, so you may be right there with the browser issue.
