### ISSUE TITLE
ProgressIndicator: Numbers are not shown correctly on IE (on animation)

### ISSUE THREAD

**Issue by EAlexRojas** [ibm-js/deliteful#548]
When there's no animation, the value is shown correctly:

![progress1](https://cloud.githubusercontent.com/assets/2373303/7156621/3e5f68d6-e368-11e4-92df-a2a6ec32c426.PNG)

But when the animation is started, the numbers are not shown properly. Running the "ProgressIndicator-percentage" sample, I have this: 

![progressindicator2](https://cloud.githubusercontent.com/assets/2373303/7157460/3ec0b174-e370-11e4-9989-458e109cd8e2.gif)

**Comment by edchat** [comment]
I am not able to reproduce this running /deliteful/samples/ProgressIndicator-percentage.html on IE11 or IE10 emulation.

**Comment by EAlexRojas** [comment]
I tested on another machines and it works fine, so apparently It was a local problem. 
I close this issue.
