### ISSUE TITLE
Fail running tests on android emulator

### ISSUE THREAD

**Issue by brunano21** [ibm-js/deliteful#562]
I'm trying the unit tests which are under tests folder, using an Android Emulator, API 19.
I followed step-by-step the guide at https://github.com/ibm-js/deliteful/tree/master/tests. So I installed the Java SDK, the Android SDK and Selendroid standalone with dependency. Furthermore I have defined the environment variables needed, eg ANDROID_HOME and JAVA_HOME and modified accordingly the PATH one.

After that, I do:
1) run the android emulator (if I skip this step, selendroid does not start automatically the emulator)
2) run java -jar selendroid-standalone-0.15-with-dependencies.jar
3) into intern.local.android.js, set the `host` variable to my host IP
3.1) (not sure about this) added `emulator: true` to intern.environments> `{ browserName: "android", platformVersion: "19", emulator: true }`
4) run from deliteful root: grunt test:local-android.

The result is the following:
**Grunt output**
http://pastebin.com/s5DDX618

**Selendroid output**
http://pastebin.com/EyRvMEWg

**Android Emulator**
http://tinypic.com/r/315baes/8

So, It's like something is misconfigured. Any suggestions?
Thanks.

**Comment by brunano21** [comment]
I've modified a bit the *tests/functional/all.js* file in order to run just the Combobox test, as following:
`define([
	"./Combobox"
]);`

Now the error I got is:
http://pastebin.com/b9HhGvA2

It seems the error is due to misconfiguration, not sure if on intern side.

**Comment by cjolif** [comment]
I'm not sure we ever intended to have the tests working on a emulator, but that's indeed an interesting subject. That said I think the forum see (http://ibm-js.github.io/deliteful/community.html) is probably a better place to handle that type of discussion.
