### ISSUE TITLE
SwapView: After calling show method with transition, Swipe transitions are broken

### ISSUE THREAD

**Issue by EAlexRojas** [ibm-js/deliteful#567]
After showing a view using a transition, swipe animation doesn't work correctly.
On the following screenshot, clicking Previous (resp. Next) calls ``showPrevious({})`` (resp. ``showNext({})``)

![swapview - new](https://cloud.githubusercontent.com/assets/2373303/7612735/e8170a20-f98c-11e4-8c5f-58163244ca57.gif)

Before clicking the button, swipe animations works perfectly, but after clicking the button, the visible view doesn't move anymore. 

Apparently, after performing the show method, the visible view still have some CSS classes related to the transition, (in this case ``-d-view-stack-slide -d-view-stack-in -d-view-stack-transition``) and that interferes with the transitions of the swipe. (more specifically with the ``transform`` property)

**Comment by dmandrioli** [comment]
Looks to be a regression since https://github.com/ibm-js/deliteful/commit/9b1cdcef35c86cb9287cb948ed6edb4f762162e9

**Comment by cjolif** [comment]
I wonder if the problem is not line 210-213. We now always return a resolve of the promise we should probably still return a resolve promised when transition is none but directly return the promise object in the other cases.

**Comment by EAlexRojas** [comment]
In fact, the problem is that on `ViewSatck` the `else` branch in the `_afterTransitionHandle` method (330 - 338) is never executed  after the update to using `Promise` instead of `dojo/Deferred`.

**Comment by cjolif** [comment]
cool, so we just miss the PR now ;) thanks @EAlexRojas.
