### ISSUE TITLE
List: race conditions when setting store in refreshRendering

### ISSUE THREAD

**Issue by mythic2** [ibm-js/deliteful#583]
I create a custom list that inherits from deliteful/list/List and attempts to set store in refreshRendering.  Code looks something like this:
```javascript
refreshRendering: function(oldValues) {
	if ('type' in oldValues) {
		var data = ... //an array created based on type information
		this.store = new dStoreMemory({data:data});
	}
```

and later on in my templates I use following code
```xml
<my-list type="blabla"></my-list>
```
I believe that it is a reasonble use of the framework. I might be wrong though :-)  However, the list is empty and I get only spinning wheel.

After some debugging I see that following happens:
1. StoreMap.attachedCallback is called - it calls this.deliver and processes pendingQueries - in my case, the code in MyList.refreshRendering is called and sets the store
2. Customelement.attachedCallback  is called - it calls this.deliver and after sets this.attached = true - in my case, StoreMap.queryStoreAndInitItems is called and it sets this._pendingQuery because the control is not attached yet. 
However nobody cares about _pendingQuery anymore, those are processed in StoreMap.attachedCallback that was already called.

**Comment by wkeese** [comment]
It seems very strange to set `this.store` in `refreshRendering()`, because `refreshRendering()` is meant for updating the rendering rather than doing internal things like that.  Looks like your code should be in `computeProperties()` instead.

Having said that, you might be hitting some bugs in the Store code too.  I've been working with @asudoh on some updates and he mentioned that `deliver()` call was wrong and removed it in https://github.com/asudoh/delite/commit/4dfc66e2817c8a44a475692a4a9cccf67f2a79e2.

**Comment by mythic2** [comment]
To be honest, the difference between ```refreshRendering()``` and ```computeProperties()``` has always felt somewhat esoteric. I get the idea, but sometimes it is difficult to draw borderline: Assigning a type, which causes store changes in my case, will result in a DOM change (items are added to the list) and therefore it should be in ```refreshRendering()```??

I know that the project is still beta and not all ideas and/or documentation are finalized. Take it as a beta feedback. I might be the first, but I am not the last who attempts to use functionality in this way :-)

**Comment by wkeese** [comment]
Your `store` property is computed based on the `type`.  Therefore it needs to be set in `computeProperties()`.   `refreshRendering()` is just for adjusting the DOM, not for changing variables that eventually affect the DOM.

Yes, it's possible that other people will make the same mistake as you, but regardless, you should still fix that mistake.

**Comment by mythic2** [comment]
I shall. And I believe that it starts to work with all suggested changes. Thank you.

**Comment by cjolif** [comment]
> And I believe that it starts to work with all suggested changes

Should this be closed now?
