### ISSUE TITLE
Combobox: Select not working

### ISSUE THREAD

**Issue by kgibb** [ibm-js/deliteful#586]
After selecting an option, the HasDropDown is not getting closed and the label is not getting updated.

**Comment by cjolif** [comment]
it used to work, so is that a recent regression you noticed? which version introduced this?

**Comment by cjolif** [comment]
Maybe related to #582

**Comment by kgibb** [comment]
Delite 0.8.x. It was working with 0.7.1. I don't think it's related to #582.

**Comment by cjolif** [comment]
can you check if you have the same behavior with deliteful 0.8.0-alpha  (not the beta)? If yes I guess this is linked to the changes from @wkeese otherwise it might  be linked to the ones from @harbalk

**Comment by kgibb** [comment]
I was using Deliteful 0.8.0-alpha with Delite 0.8.0-beta.2. Moving Deliteful to 0.8.0-beta has resolved the issue.
