### ISSUE TITLE
Memory leak in ViewStack

### ISSUE THREAD

**Issue by kgibb** [ibm-js/deliteful#593]
When the selected child is removed from the ViewStack, the _visibleChild property still references the detached node. 

The _visibleChild property isn't nullified/re-assigned until (and if) show is called again. 

We're dynamically showing/hiding nodes and there are instances where the view stack can be empty. 

Perhaps ViewStack should do a superCall on Container.removeChild or listen for delite-remove-child and nullify _visibleChild if needed.

**Comment by wkeese** [comment]
Sure, makes sense.
