### ISSUE TITLE
Scrollable Container: unable to highlight underlying text fields 

### ISSUE THREAD

**Issue by rmobrien12** [ibm-js/deliteful#599]
When you have input fields within scrollable containers the input text is not selectable in Internet Explorer 11 (Chrome and Firefox work fine). 
You can demo this bug here http://jsfiddle.net/p9rd3d62/1/ 

It might be from the delite code in Scrollable.js
![image](https://cloud.githubusercontent.com/assets/13907318/13395803/f562667e-dee8-11e5-81c9-6e144259859b.png)
This event seems to only be triggered in IE and it sets user-select to none.

**Comment by wkeese** [comment]
I assume that code is there so the user doesn't accidentally select text when he's trying to scroll (on a mobile device), but maybe the code should just be removed.
