### ISSUE TITLE
delite/register unregister missing

### ISSUE THREAD

**Issue by gbaumgart** [ibm-js/deliteful#622]
Hi,
there is currently no clean way (can only fork and re-map the module to own impl.) to unregister a type. It would be fully enough to expose just  "registry" as module export so I can take it from there. 
close this just if it's not really of your concern. 
Thanks.

**Comment by wkeese** [comment]
What would it mean exactly to "unregister a type"?

The problem, at least on browsers like Chrome that natively support `document.registerElement()`, is that there's no way to unregister an element.   So I don't see how it can help you to access the `registry` property.   Let me know if I'm missing something.

**Comment by gbaumgart** [comment]
ah, didn't know about chrome yet. thanks. 
yes, it was about re-registering a type. 
ok then, closing.
