### ISSUE TITLE
run remote Intern tests against Firefox 45 not Firefox 31

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#633]
Upgrade the Intern tests to run against Firefox 45 or 46.  (Firefox 47 is the latest version but it isn't available on SauceLabs yet.)

It's not a trivial change though because it's getting some regression test failures:

```
× firefox 45 on Windows 7 - unit tests - list/PageableList - Loading all next pages, and then loading all previous pages (pageLength 20, maxPages 2) (3.483s)
CancelError: Timeout reached on firefox 45 on Windows 7 - unit tests - list/PageableList - Loading all next pages, and then loading all previous pages (pageLength 20, maxPages 2)
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:132:20>
× firefox 45 on Windows 7 - unit tests - list/PageableList - Add items in displayed pages (3.101s)
CancelError: Timeout reached on firefox 45 on Windows 7 - unit tests - list/PageableList - Add items in displayed pages
  at Test.prototype.restartTimeout/this._timer<  <__intern/lib/Test.js:132:20>
× firefox 45 on Windows 7 - ScrollableContainer - functional - scroll with animation (via button, inside LinearLayout, scrollDirection=vertical) (185.244s)
ScriptTimeout: [POST http://(redacted)@localhost:4444/wd/hub/session/8e9224331b15441b90f8b77a11481dd9/execute_async / {"scri
× firefox 45 on Windows 7 - Toaster tests - Check visibility on hover (10.801s)
AssertionError: msgbutton13 was not found
```

cc @brunano21

**Comment by brunano21** [comment]
I've run List unit tests on both Win7/FF45 local VM and SauceLabs and I'm not getting errors like yours.
Also, not sure if relevant, I'm using selenium server `v2.53.0`.
Here you can see the logs for the [local VM](http://pastebin.com/WyCmVL0a) execution and [SauceLab](http://pastebin.com/EAz6SdzG) exectution.

**Comment by wkeese** [comment]
The problem happens when running the full test suite, but not when just running the List unit tests.

**Comment by wkeese** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/java/CHANGELOG#L272 says that native event support was discontinued after FF31.

**Comment by wkeese** [comment]
Finally upgraded to FF53, in 07c19806df1994029b5959fcc75440d6c02109ee.
