### ISSUE TITLE
Slider : is moving ?

### ISSUE THREAD

**Issue by gbaumgart** [ibm-js/deliteful#654]
Hi,
is there a way to determine whether the user is currently sliding ? For instance, if the user is dragging the knob or holds cursor keys, I need to prevent certain 2-way updates on that slider, til the user is finish.

or is there a shortcut solution to archive the same ?

**Comment by wkeese** [comment]
There's no official way to do that.   I suppose you could set a flag to true on the `pointerdown` event and false on the `pointerup` event.   And for keyboard, by checking if `document.activeElement` is a descendant of the slider's root node.

In the future, can you send questions to https://groups.google.com/forum/embed/?place=forum/delite-users#!forum/delite-users?   This is a bug database, not a question forum.

**Comment by gbaumgart** [comment]
ups, didn't saw your comment. thanks Bill. will do so.
