### ISSUE TITLE
no header and bottom toolbar on iphone

### ISSUE THREAD

**Issue by xblox** [ibm-js/deliteful#693]
Hi,
I just made some tests on a ios10.2.1 for all demos/* : 

Both apps end up the same way: the header and bottom toolbar is not shown, it shows it for a short moment when you click around but its 'faded' off again as soon the new view comes in. 

Can you check please ? I don't need the bottom bar but definitely the header toolbar (for back button and popup menu)

thanks.

**Comment by wkeese** [comment]
I'm not sure what you are talking about.  header toolbar?   Is it something from deliteful, or from the browser?

**Comment by xblox** [comment]
hi,
well, if you open deliteful/demos/mobileapp in the browser, you'll see a top and bottom bar. these toolbars disappear on iphone but I am not sure this is because of a bug or incomplete styling of the demo sources. 

g

**Comment by xblox** [comment]
closing this, we're moving to "ionic" :-(
