### ISSUE TITLE
ComboPopup: needs [x] close icon to support VoiceOver

### ISSUE THREAD

**Issue by wkeese** [ibm-js/deliteful#710]
On desktop you can easily close the deliteful/Combobox dropdown by clicking somewhere else on the screen or by using the ESC key.

But on iOS there no way to close the popup using VoiceOver except by selecting something from the list.  And it might be impossible for a user to select something from the dropdown list because:

- see for example the second to last example in deliteful/tests/functional/ComboPopup.html where the user has to type certain (unknown) three character sequences to trigger anything to appear in the list
- there might be a situation where there's just no data to populate the list regardless of what the user types in the filter

So I think we need to have a [x] icon on the ComboPopup dialog (i.e. the Combobox popup on mobile).

**Comment by brunano21** [comment]
👍
